kind = "web"
previewPath = "/"
title = "TechConnect360Degree"
version = "1.0.0"
id = "artifacts/techconnect360"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19386

[services.development]
run = "pnpm --filter @workspace/techconnect360 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/techconnect360", "run", "build" ]
publicDir = "artifacts/techconnect360/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19386"
BASE_PATH = "/"
